// Deterministic CV renderer: Profile -> clean Markdown, no LLM required. Shared by the CLI's
// no-key fallback and the web app's live preview. The LLM rewrite step (generation-spec.md) is a
// separate, optional enhancement; this renderer never invents content, it only lays out what the
// Profile already contains.

import { taxonomy } from './load.js';
import type { Profile, Bullet, TaxonomyCategoryId } from './types.js';

function categoryName(id: string): string {
  return taxonomy.categories.find((c) => c.id === id)?.name ?? id;
}

function fmtDate(d?: string): string {
  if (!d) return '';
  if (d.toLowerCase() === 'present') return 'Present';
  const [y, m] = d.split('-');
  if (!m) return y ?? d;
  const months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[parseInt(m, 10)] ?? ''} ${y}`.trim();
}

function renderBullet(b: Bullet): string {
  if (b.rendered) return b.rendered;
  const parts = [b.action];
  if (b.system) parts.push(`on ${b.system}`);
  if (b.tech?.length) parts.push(`(${b.tech.join(', ')})`);
  let line = parts.join(' ');
  if (b.metric) line += ` - ${b.metric}`;
  return line;
}

export interface RenderOptions {
  footer?: boolean;
}

/** Render a Profile to a clean Markdown CV. Pure and deterministic. */
export function renderCv(profile: Profile, options: RenderOptions = {}): string {
  const out: string[] = [];
  const id = profile.identity;

  // Header
  out.push(`# ${id.name}`);
  const headline = profile.headline?.text ?? profile.target?.roleLabel ?? '';
  const contactBits = [id.location, id.email, id.phone].filter(Boolean);
  const headerLine = [headline ? `**${headline}**` : '', ...contactBits].filter(Boolean).join(' | ');
  if (headerLine) out.push(headerLine);
  const links = (profile.links ?? []).map((l) => `[${l.label ?? l.type}](${l.url})`);
  if (links.length) out.push(links.join(' | '));
  out.push('');

  // Summary
  if (profile.summary?.text) {
    out.push(`> ${profile.summary.text}`, '');
  }

  // Skills, grouped by taxonomy category (in taxonomy order)
  const skills = profile.skills ?? [];
  if (skills.length) {
    out.push('## Skills');
    for (const cat of taxonomy.categories) {
      const inCat = skills.filter((s) => s.category === (cat.id as TaxonomyCategoryId));
      if (inCat.length) out.push(`- **${cat.name}:** ${inCat.map((s) => s.name).join(', ')}`);
    }
    out.push('');
  }

  // Experience
  const experience = profile.experience ?? [];
  if (experience.length) {
    out.push('## Experience');
    for (const e of experience) {
      const dates = [fmtDate(e.startDate), fmtDate(e.endDate)].filter(Boolean).join(' - ');
      const head = [`${e.title} - ${e.org}`, e.location, dates].filter(Boolean).join(', ');
      out.push(`### ${head}`);
      for (const b of e.bullets ?? []) out.push(`- ${renderBullet(b)}`);
      out.push('');
    }
  }

  // Projects
  const projects = profile.projects ?? [];
  if (projects.length) {
    out.push('## Projects');
    for (const p of projects) {
      const name = p.repo ? `[${p.name}](${p.repo})` : p.name;
      const stats = [p.stars ? `${p.stars} stars` : '', p.usage].filter(Boolean).join(', ');
      const desc = [p.shipped ?? p.role, stats].filter(Boolean).join('. ');
      out.push(`- **${name}**${desc ? ` - ${desc}` : ''}`);
    }
    out.push('');
  }

  // Publications
  const pubs = profile.publications ?? [];
  if (pubs.length) {
    out.push('## Publications');
    for (const p of pubs) {
      const v = [p.venue, p.year].filter(Boolean).join(', ');
      out.push(`- ${p.url ? `[${p.title}](${p.url})` : p.title}${v ? ` - ${v}` : ''}`);
    }
    out.push('');
  }

  // Education
  const edu = profile.education ?? [];
  if (edu.length) {
    out.push('## Education');
    for (const e of edu) {
      const deg = [e.degree, e.field].filter(Boolean).join(', ');
      out.push(`- ${deg ? `${deg} - ` : ''}${e.institution}${e.year ? `, ${e.year}` : ''}`);
    }
    out.push('');
  }

  // Certifications
  const certs = profile.certifications ?? [];
  if (certs.length) {
    out.push('## Certifications');
    for (const c of certs) {
      out.push(`- ${c.name}${c.issuer ? ` - ${c.issuer}` : ''}${c.year ? `, ${c.year}` : ''}`);
    }
    out.push('');
  }

  if (options.footer !== false) {
    out.push(
      '<!-- Generated by AIEngineerCV (https://github.com/sebuzdugan/AIEngineerCV), built by @sebuzdugan -->',
    );
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}
